server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  threads:
    virtual:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

web:
  cors:
    allowed-origins: "http://localhost:8082,http://localhost:8089"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"