server:
  port: 8081
  servlet:
    context-path: /resource-server
  tomcat:
    max-connections: 8192
    accept-count: 100

spring:
  threads:
    virtual:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

web:
  cors:
    allowed-origins: "http://localhost:8082,http://localhost:8089"
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "*"
    exposed-headers: "Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Access-Control-Allow-Methods,Access-Control-Max-Age,Access-Control-Allow-Headers"

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics
    access:
      default: none
  endpoint:
    health:
      access: read-only
    info:
      access: read-only
    beans:
      access: read-only
    metrics:
      access: read-only